### ISSUE TITLE
use orthographic projection

### ISSUE THREAD

**Issue by fenn** [philipturner/rod-logic#1]
it's hard to see what's going on in [some of the figures](https://raw.githubusercontent.com/philipturner/rod-logic/main/Documentation/RodActuation_Frame1.jpg) because the visual distortion in the crystal lattice makes it look like there might be some kind of important structure there, even though it's just moire / aliasing artifacts.

it would be simpler and easier to read all of the diagrams if they were in orthographic projection. straight lines would look straight, and there would be no false sense of vast scale...

**Comment by philipturner** [comment]
I'm just taking screenshots of a CAD program. It has 3D rendering, and the images taken are all in perspective view. Ideally, I'd take a video or provide an interactive experience, where you can look at the scene in perspective view.

Regarding orthographic projection, I have many hand-drawn drawings of this hardware. Some of those are in orthographic projection. Just not published.

Thanks for the feedback.

**Comment by philipturner** [comment]
There are multiple ways I could produce an orthographic render. I'll note to do that for future documentation, especially if I publish anything professional.

**Comment by philipturner** [comment]
I have adopted pseudo-orthographic views (30° FOV) with white backgrounds as the default for all media. In addition, static images now have higher resolution and ray tracing with higher sample count (less noise). Going to close this issue now.

![SheetAxleSystem_FullMinimization](https://github.com/philipturner/rod-logic/assets/71743241/3e49d833-b953-465e-8e3f-d88523b14f4e)
